### ISSUE TITLE
Angular2 version not working in FF, source maps, runtime errors

### ISSUE THREAD

**Issue by maryo** [frankwallis/tower#1]
Hi. I'm trying to choose a workflow for TypeScript + angular project. Looks like JSPM with your plugin-typescript has the most straightforward workflow to me. So i checked the example (this repo).

The angular2 branch doesn't work in FireFox.
The master branch does work in FF but it takes almost 10 seconds to load it which is not acceptable. Do you know why? Is it a problem with JSPM/SystemJS loader? Have you noticed? It's quite fast to load it in Chrome.

Source maps:
When using console.log, it works fine, awesome!
getting available for 0 - hand.ts:31

But when trying a runtime error:
angular2.dev.js:9842 `ReferenceError: foo is not defined in [availableCards in <li class="hand-card" *for="#card of availableCards">]`

Are these issues somehow solvable?
BTW thanks for your work.

**Comment by frankwallis** [comment]
Apologies for not getting back to you before, I think the angular2 example is now working.
